### PR TITLE
3342: Move HTML formatting into localisation file

### PR DESCRIPTION
**Pull request by vixus0**
The template shouldn't constrain how the content for the why-companies
page can be formatted (within reason).

Author: @vixus0

### CODE REVIEW

**Comment by Veda** [comment]
I would like the formatting to be in the view rather than being localised. I don't see a reason why you should be localising the html formatting ? Am i missing some context here @vixus0 ?

**Comment by vixus0** [comment]
There are a couple of reasons, that are similar to why we put the formatting for IDP descriptions in the localisation config files:

* We're confusing layout formatting (the view) with content formatting (the localisation file).
* Modifying content should not require changing the view.
* There's no reason we should be forcing translators to use exactly five paragraphs.
* There may be additional HTML elements required (`<em>` etc.) that are unavailable using the current structure.

**Comment by willp-bl** [comment]
👍 good to have flexibility around the content

**Comment by Veda** [comment]
Ah, that makes sense with paragraph as examples. 👍

**Pull request merged**
