### PR TITLE
3564: Added welsh translations

### PR DESCRIPTION
**Pull request by Veda**
Authors: @veda

### CODE REVIEW

**Comment by robinwhittleton** [comment]
Do we want to change the updated date? We’re translating but not altering the meaning of the content, and it might feel a bit odd to have a different date to the versions if the user switches between them.

**Comment by Veda** [comment]
@robinwhittleton you are right.. I shall change it to 27th April perhaps so it is same as english version.

**Comment by oswaldquek** [comment]
@robinwhittleton @Veda I'm confused - where is this updated date?

**Comment by Veda** [comment]
It was all the way at the bottom of the privacy-notice file, since i put it back to what i was it isn't showing up in the changes :)

**Comment by oswaldquek** [comment]
Ok. Best to comment on the line itself in the code in the future :)

**Pull request merged**
