### PR TITLE
BAU: Enable prove-identity for loa1 journeys

### PR DESCRIPTION
**Pull request by tomrosier**
To enable Italy to use our services at LOA1

### CODE REVIEW

**Comment by CharlesIC** [comment]
@jakubmiarka We might need your input on this

This change will enable eIDAS for all LOA1 services that also have eIDAS enabled, however, we don’t want services to be able to access eIDAS with LOA1. We only want Test RP in integration to initiate an eIDAS journey at LOA1 (because Italy test credentials are LOA1).
Now - it may be that all services that have eIDAS enabled flag are also at least LOA2 - in that case that’s fine (but flimsy)
Hub-fed-config only says whether `eidasEnabled` is true or false for each service and the LOA the service supports. We have this this blanket block for LOA1 + eIDAS that that this change would remove, so we have to make sure this is the right thing to do or find a workaround.

**Comment by jakubmiarka** [comment]
The assumption is correct, the users will not be redirected to `prove-identity` if the transaction doesn't support eidas. Which is only set on LOA2 services, otherwise people would be already being redirected to that page with 404 (as it's constrained). So its' already flimsy.
You can test this without making a frontend change - enable the eidas on the test-rp-loa1 (or whichever you're using) and go manually to `/choose-a-country` and there you are. Assuming there are no further changes required in the hub/policy... 
If you're worried about the LOA1+eIDAS block I'd suggest adding additional check for LOA on this line: https://github.com/alphagov/verify-frontend/blob/b21c86b3df9f99c8cec00c150c064fa630d39fd5/app/controllers/authn_request_controller.rb#L107 and this validator: https://github.com/alphagov/verify-frontend/blob/master/app/controllers/partials/eidas_validation_partial_controller.rb

**Comment by CharlesIC** [comment]
Thanks @jakubmiarka , that's super helpful.

@tomrosier fine to apply this change given what Jakub has said, just add his suggested change to do more checks.

**Comment by Wynndow** [comment]
@CharlesIC STOP DOING WORK

**Pull request closed without merging**
