### PR TITLE
BAU: upgrade from accessible-typeahead v0.3.1 to accessible-autocompl…

### PR DESCRIPTION
**Pull request by hugh-emerson**
…ete v1.6.1

To be merged at the same time as https://github.com/alphagov/ida-hub-acceptance-tests/pull/22

Solo: @hugh-emerson

### CODE REVIEW

**Comment by jakubmiarka** [comment]
Oh perfect, I already had a ticket for this [TT-1493](https://govukverify.atlassian.net/browse/TT-1493)

**Comment by hugh-emerson** [comment]
Ah, don't merge - I've found an issue.

**Comment by willp-bl** [comment]
Is the issue fixed?

**Comment by hugh-emerson** [comment]
Need a bit of time to look into this and the impact on our selenium test.

**Pull request closed without merging**
